### ISSUE TITLE
Question: Any news on demo for NativesScript Angular ?

### ISSUE THREAD

**Issue by dotnetdreamer** [triniwiz/nativescript-webkit-webview#2]
Hi,
i just wanted to know if there is any demo source to include this plugin i NativeScript Angular ?

**Comment by sean-perkins** [comment]
```
registerElement(
    'TNSWebView',
    () => require('nativescript-webkit-webview').TNSWKWebView
);
```

Is the only thing you need to for almost 99% of NativeScript to NativeScript Angular implementations.
